export type Item = { name: string; tier: number };
 
export const audiences: Item[] = [
  // Tier 1
  { name: "Restaurantes Locais", tier: 1 }, { name: "Personal Trainers", tier: 1 }, { name: "Pousadas e Hostels", tier: 1 },
  { name: "Motoristas de Aplicativo", tier: 1 }, { name: "Manicures e Salões de Beleza", tier: 1 }, { name: "Vendedores de E-commerce", tier: 1 },
  { name: "Padeiros Artesanais", tier: 1 }, { name: "Floriculturas", tier: 1 }, { name: "Pet Walkers", tier: 1 },
  { name: "Fotógrafos de Casamento", tier: 1 }, { name: "Bares e Lanchonetes", tier: 1 }, { name: "Entregadores", tier: 1 },
  { name: "Professores Particulares", tier: 1 }, { name: "Costureiras", tier: 1 }, { name: "Padarias", tier: 1 },
  { name: "Mercadinhos de Bairro", tier: 1 }, { name: "Lava-Rápidos", tier: 1 }, { name: "Academias de Musculação", tier: 1 },
  { name: "Pet Shops", tier: 1 }, { name: "Lojas de Roupas", tier: 1 }, { name: "Autoescolas", tier: 1 },
  { name: "Farmácias de Bairro", tier: 1 }, { name: "Barbearias", tier: 1 }, { name: "Vidraçarias", tier: 1 },
  { name: "Serralherias", tier: 1 }, { name: "Pintores e Pedreiros", tier: 1 },
  // Tier 2
  { name: "Corretores de Imóveis", tier: 2 }, { name: "Advogados Autônomos", tier: 2 }, { name: "Empresas de Limpeza", tier: 2 },
  { name: "Guias Turísticos", tier: 2 }, { name: "Encanadores e Eletricistas", tier: 2 }, { name: "Borracharias", tier: 2 },
  { name: "Gráficas e Copiadoras", tier: 2 }, { name: "Lojas de Suplementos", tier: 2 }, { name: "Auto Peças", tier: 2 },
  { name: "Distribuidoras de Bebidas", tier: 2 }, { name: "Transportadoras Locais", tier: 2 }, { name: "Oficinas de Costura", tier: 2 },
  { name: "Agências de Turismo", tier: 2 }, { name: "Concessionárias de Seminovos", tier: 2 }, { name: "Casas de Festas", tier: 2 },
  { name: "Buffets Infantis", tier: 2 }, { name: "Empreiteiras", tier: 2 }, { name: "Clínicas Odontológicas Populares", tier: 2 },
  { name: "Despachantes", tier: 2 }, { name: "Escolas de Trânsito", tier: 2 }, { name: "Estúdios Fotográficos", tier: 2 },
  { name: "Clínicas de Fisioterapia", tier: 2 }, { name: "Agências de Intercâmbio", tier: 2 },
  // Tier 3
  { name: "Nutricionistas Esportivos", tier: 3 }, { name: "Escolas de Idiomas Bilingues", tier: 3 }, { name: "Arquitetos", tier: 3 },
  { name: "Contadores", tier: 3 }, { name: "Consultores Financeiros", tier: 3 }, { name: "Produtores de Cerveja Artesanal", tier: 3 },
  { name: "Coworkings e Espaços Compartilhados", tier: 3 }, { name: "Escritórios de Engenharia", tier: 3 }, { name: "Oficinas de Funilaria Premium", tier: 3 },
  { name: "Produtores de Alimentos Orgânicos", tier: 3 }, { name: "Consultores de RH", tier: 3 }, { name: "Síndicos Profissionais", tier: 3 },
  { name: "Clínicas de Estética Avançada", tier: 3 }, { name: "Escolas de Música e Artes", tier: 3 }, { name: "Assessorias de Imprensa", tier: 3 },
  { name: "Corretoras de Seguros", tier: 3 }, { name: "Escritórios de Design de Interiores", tier: 3 }, { name: "Psicólogos Clínicos", tier: 3 },
  { name: "Terapeutas Holísticos", tier: 3 }, { name: "Clínicas de Acupuntura", tier: 3 }, { name: "Acampamentos de Férias", tier: 3 },
  { name: "Galerias de Arte Locais", tier: 3 },
  // Tier 4
  { name: "Especialistas em Implantes Dentários", tier: 4 }, { name: "Clínicas de Cirurgia Plástica", tier: 4 }, { name: "Fábricas de Software Bootstrapped", tier: 4 },
  { name: "Agências de Viagem de Luxo", tier: 4 }, { name: "Hospitais Veterinários 24h", tier: 4 }, { name: "Construtoras de Alto Padrão", tier: 4 },
  { name: "Joalherias Customizadas", tier: 4 }, { name: "Estúdios de Yoga e Mindfulness", tier: 4 }, { name: "Produtoras Audiovisuais e de Cinema", tier: 4 },
  { name: "Hospitais e Maternidades Particulares", tier: 4 }, { name: "Gestores de Patrimônio (Family Offices)", tier: 4 }, { name: "Concessionárias de Veículos de Luxo", tier: 4 },
  { name: "Consultorias Tributárias Especializadas", tier: 4 }, { name: "Clínicas de Dermatologia Estética", tier: 4 }, { name: "Escritórios de Advocacia Corporativa", tier: 4 },
  { name: "Importadoras de Vinhos Premium", tier: 4 }, { name: "Clubes de Golfe e Tiro", tier: 4 }, { name: "Clínicas de Reprodução Humana", tier: 4 },
  { name: "Aprendizagem de idiomas por vídeos curtos", tier: 4 }, { name: "Simulador de entrevistas de emprego", tier: 4 }, { name: "Marketplace hiperlocal", tier: 4 },
  { name: "Comunidade de empreendedores", tier: 4 }, { name: "Reality show digital", tier: 4 }, { name: "Competições de criatividade", tier: 4 },
  { name: "Aprendizagem gamificada de idiomas", tier: 4 }, { name: "Fitness com rankings sociais", tier: 4 }, { name: "Rede de inventores", tier: 4 },
  { name: "Banco de ideias monetizáveis", tier: 4 }, { name: "Clube dos empreendedores", tier: 4 }, { name: "Passaporte digital de viagens", tier: 4 },
  { name: "Liga de músicos", tier: 4 }, { name: "Fantasy esportivo local", tier: 4 }, { name: "Fashion battle", tier: 4 },
  { name: "Detector de tendências", tier: 4 }, { name: "Comunidade de startups", tier: 4 }, { name: "Campeonato global de habilidades", tier: 4 },
  { name: "Ecossistema de missões e recompensas", tier: 4 }, { name: "Jovens sem plano de carreira", tier: 4 }, { name: "Universitários indecisos", tier: 4 },
  { name: "Profissionais insatisfeitos", tier: 4 }, { name: "Pessoas em transição de carreira", tier: 4 }, { name: "Recém-formados desempregados", tier: 4 },
  { name: "Pessoas procurando propósito", tier: 4 }, { name: "Pessoas que querem recomeçar", tier: 4 }, { name: "Pessoas que não sabem o que estudar", tier: 4 },
  { name: "Pessoas que vivem sozinhas", tier: 4 }, { name: "Idosos solitários", tier: 4 }, { name: "Nômades digitais", tier: 4 },
  { name: "Estudantes deslocados", tier: 4 }, { name: "Trabalhadores remotos", tier: 4 }, { name: "Divorciados recentes", tier: 4 },
  { name: "Pais solteiros", tier: 4 }, { name: "Imigrantes", tier: 4 }, { name: "Expatriados", tier: 4 },
  { name: "Pessoas tímidas", tier: 4 }, { name: "Pais ocupados", tier: 4 }, { name: "Executivos", tier: 4 },
  { name: "Pequenos empresários", tier: 4 }, { name: "Estudantes universitários", tier: 4 }, { name: "Profissionais de saúde", tier: 4 },
  { name: "Professores", tier: 4 }, { name: "Freelancers", tier: 4 }, { name: "Consultores", tier: 4 },
  { name: "Criadores de conteúdo", tier: 4 }, { name: "Donos de lojas", tier: 4 }, { name: "Pessoas que procrastinam", tier: 4 },
  { name: "Pessoas sem disciplina", tier: 4 }, { name: "Pessoas querendo hábitos melhores", tier: 4 }, { name: "Pessoas querendo acordar cedo", tier: 4 },
  { name: "Pessoas buscando foco", tier: 4 }, { name: "Pessoas querendo ganhar dinheiro online", tier: 4 }, { name: "Pessoas querendo criar startups", tier: 4 },
  { name: "Pessoas querendo aprender IA", tier: 4 }, { name: "Pessoas querendo aprender programação", tier: 4 }, { name: "Pessoas querendo viralizar no TikTok", tier: 4 },
  { name: "Pessoas querendo viralizar no YouTube", tier: 4 }, { name: "Pessoas querendo criar conteúdo automaticamente", tier: 4 }, { name: "Pessoas querendo automatizar negócios", tier: 4 },
  { name: "Pessoas querendo criar aplicativos", tier: 4 }, { name: "Pessoas querendo criar SaaS", tier: 4 }, { name: "Usuários de IA", tier: 4 },
  { name: "Pessoas buscando renda extra", tier: 4 }, { name: "Empreendedores solo", tier: 4 }, { name: "Estudantes", tier: 4 },
  { name: "Pessoas aprendendo inglês", tier: 4 }, { name: "Pessoas querendo emagrecer", tier: 4 }, { name: "Gamers mobile", tier: 4 },
  { name: "Donos de pequenos negócios", tier: 4 }, { name: "Usuários de Notion", tier: 4 }, { name: "Usuários de ChatGPT", tier: 4 },
  { name: "Pessoas com ansiedade", tier: 4 }, { name: "Casais", tier: 4 }, { name: "Pais de primeira viagem", tier: 4 },
  { name: "Investidores iniciantes", tier: 4 }, { name: "Motoristas de aplicativos", tier: 4 }, { name: "Donos de cães", tier: 4 },
  { name: "Donos de gatos", tier: 4 }, { name: "Gamers", tier: 4 }, { name: "Corredores", tier: 4 },
  { name: "Ciclistas", tier: 4 }, { name: "Fotógrafos", tier: 4 }, { name: "Músicos", tier: 4 },
  { name: "Pessoas que falham entrevistas", tier: 4 }, { name: "Pessoas que não conseguem vender", tier: 4 }, { name: "Pessoas que não conseguem estudar", tier: 4 },
  { name: "Pessoas que não conseguem poupar", tier: 4 }, { name: "Pessoas que não conseguem manter hábitos", tier: 4 }, { name: "Pessoas que querem criar conteúdo", tier: 4 },
  { name: "Pessoas que querem abrir negócios", tier: 4 }, { name: "Pessoas que querem trabalhar remotamente", tier: 4 }, { name: "Pessoas que querem aprender IA", tier: 4 },
  { name: "Pessoas que querem mudar de profissão", tier: 4 }, { name: "Pessoas que querem emigrar", tier: 4 }, { name: "Pessoas que querem aprender inglês", tier: 4 },
  { name: "Pessoas que querem aprender programação", tier: 4 }, { name: "Pessoas que querem ganhar dinheiro online", tier: 4 }, { name: "Pessoas que querem investir", tier: 4 },
  { name: "Pessoas que querem empreender", tier: 4 }, { name: "Pessoas que querem melhorar produtividade", tier: 4 }, { name: "Pessoas que querem organizar a vida", tier: 4 },
  { name: "Pessoas que querem gerir tempo", tier: 4 }, { name: "Pessoas que querem reduzir ansiedade", tier: 4 }, { name: "Pessoas sem organização", tier: 4 },
  { name: "Pessoas que gastam demasiado dinheiro", tier: 4 }, { name: "Pessoas que abandonam metas", tier: 4 }, { name: "Pessoas que têm dificuldade em decidir", tier: 4 },
  { name: "Profissionais em mudança de carreira", tier: 4 }, { name: "Compradores de imóveis", tier: 4 }, { name: "Fundadores de startups", tier: 4 },
  { name: "Estudantes de medicina", tier: 4 }, { name: "Estudantes de engenharia", tier: 4 }, { name: "Designers", tier: 4 },
  { name: "Pesquisadores", tier: 4 }, { name: "Advogados", tier: 4 }, { name: "Médicos", tier: 4 },
  { name: "Gestores", tier: 4 }, { name: "Empreendedores", tier: 4 }, { name: "Profissionais que esquecem informações", tier: 4 },
  { name: "Explicadores", tier: 4 }, { name: "PALOP", tier: 4 }, { name: "Pequenos comerciantes africanos", tier: 4 },
  { name: "Estudantes africanos", tier: 4 }, { name: "Pequenos comerciantes", tier: 4 }, { name: "Pequenos negócios", tier: 4 },
  { name: "Pequenos negócios africanos", tier: 4 }, { name: "Microempresas", tier: 4 }, { name: "Microempresas africanas", tier: 4 },
  { name: "Comerciantes de mercados", tier: 4 }, { name: "Agricultores familiares", tier: 4 }, { name: "Taxistas", tier: 4 },
  { name: "Mototaxistas", tier: 4 }, { name: "Pescadores", tier: 4 }, { name: "Vendedores ambulantes", tier: 4 },
  { name: "Pequenas lojas", tier: 4 }, { name: "Igrejas", tier: 4 }, { name: "Escolas privadas", tier: 4 },
  { name: "Clínicas locais", tier: 4 }, { name: "Pequenas igrejas", tier: 4 }, { name: "Salões de beleza", tier: 4 },
  { name: "Oficinas mecânicas", tier: 4 }, { name: "Imobiliárias locais", tier: 4 }, { name: "Advogados independentes", tier: 4 },
  { name: "Criadores de cursos", tier: 4 }, { name: "Youtubers africanos", tier: 4 }, { name: "Influenciadores africanos", tier: 4 },
  { name: "Rádios locais", tier: 4 }, { name: "Estudantes do ensino médio", tier: 4 }, { name: "Universitários", tier: 4 },
  { name: "Estudantes de direito", tier: 4 }, { name: "Explicadores particulares", tier: 4 }, { name: "Diretores escolares", tier: 4 },
  { name: "Enfermeiros", tier: 4 }, { name: "Nutricionistas", tier: 4 }, { name: "Psicólogos", tier: 4 },
  { name: "Fisioterapeutas", tier: 4 }, { name: "Dentistas", tier: 4 }, { name: "Contabilistas", tier: 4 },
  { name: "Auditores", tier: 4 }, { name: "Programadores", tier: 4 }, { name: "Cientistas de dados", tier: 4 },
  { name: "Analistas de sistemas", tier: 4 }, { name: "Designers gráficos", tier: 4 }, { name: "Designers UX/UI", tier: 4 },
  { name: "YouTubers", tier: 4 }, { name: "TikTokers", tier: 4 }, { name: "Influenciadores", tier: 4 },
  { name: "Streamers", tier: 4 }, { name: "Podcasters", tier: 4 }, { name: "Bloggers", tier: 4 },
  { name: "Copywriters", tier: 4 }, { name: "Gestores de marketing", tier: 4 }, { name: "Vendedores", tier: 4 },
  { name: "Corretores imobiliários", tier: 4 }, { name: "Coaches", tier: 4 }, { name: "Empresários", tier: 4 },
  { name: "Assistentes virtuais", tier: 4 }, { name: "Comerciantes", tier: 4 }, { name: "Donos de restaurantes", tier: 4 },
  { name: "Donos de bares", tier: 4 }, { name: "Donos de academias", tier: 4 }, { name: "Agricultores", tier: 4 },
  { name: "Pecuaristas", tier: 4 }, { name: "Transportadores", tier: 4 }, { name: "Motoristas de táxi", tier: 4 },
  { name: "Mecânicos", tier: 4 }, { name: "Eletricistas", tier: 4 }, { name: "Canalizadores", tier: 4 },
  { name: "Carpinteiros", tier: 4 }, { name: "Pedreiros", tier: 4 }, { name: "Engenheiros civis", tier: 4 },
  { name: "Técnicos de informática", tier: 4 }, { name: "Funcionários públicos", tier: 4 }, { name: "Policiais", tier: 4 },
  { name: "Militares", tier: 4 }, { name: "Jornalistas", tier: 4 }, { name: "DJs", tier: 4 },
  { name: "Artistas digitais", tier: 4 }, { name: "Donos de pets", tier: 4 }, { name: "Mães solteiras", tier: 4 },
  { name: "Aposentados", tier: 4 }, { name: "Idosos ativos", tier: 4 }, { name: "Pessoas com deficiência", tier: 4 },
  { name: "Desempregados", tier: 4 }, { name: "Pessoas em mudança de carreira", tier: 4 }, { name: "Traders", tier: 4 },
  { name: "Investidores imobiliários", tier: 4 }, { name: "Compradores online", tier: 4 }, { name: "Vendedores online", tier: 4 },
  { name: "Afiliados digitais", tier: 4 }, { name: "Atletas amadores", tier: 4 }, { name: "Praticantes de musculação", tier: 4 },
  { name: "Pessoas em dieta", tier: 4 }, { name: "Pessoas aprendendo programação", tier: 4 }, { name: "Pessoas aprendendo IA", tier: 4 },
  { name: "Solteiros", tier: 4 }, { name: "Pessoas divorciadas", tier: 4 }, { name: "Líderes religiosos", tier: 4 },
  { name: "Gestores de comunidades", tier: 4 }, { name: "Recém-formados", tier: 4 }, { name: "Candidatos a concursos", tier: 4 },
  { name: "Profissionais de RH", tier: 4 }, { name: "Pequenas empresas", tier: 4 }, { name: "Donos de e-commerce", tier: 4 },
  { name: "Programadores juniores", tier: 4 }, { name: "Programadores seniores", tier: 4 }, { name: "Gestores de equipas", tier: 4 },
  { name: "Donos de salões", tier: 4 }, { name: "Clínicas privadas", tier: 4 }, { name: "Afiliados", tier: 4 },
  { name: "Transportadoras", tier: 4 }, { name: "Motoristas", tier: 4 }, { name: "Mães trabalhadoras", tier: 4 },
  { name: "Pais de adolescentes", tier: 4 }, { name: "Profissionais remotos", tier: 4 }, { name: "Corretores", tier: 4 },
  { name: "Pessoas com insônia", tier: 4 }, { name: "Pessoas sedentárias", tier: 4 }, { name: "Pessoas obesas", tier: 4 },
  { name: "Estudantes de inglês", tier: 4 }, { name: "Estudantes de programação", tier: 4 }, { name: "Estudantes de IA", tier: 4 },
  { name: "Donos de oficinas", tier: 4 }, { name: "ONGs", tier: 4 }, { name: "Músicos independentes", tier: 4 },
  { name: "Equipas de eSports", tier: 4 }, { name: "Estudantes do secundário", tier: 4 }, { name: "Jovens empreendedores", tier: 4 },
  { name: "Startups", tier: 4 }, { name: "Fundadores SaaS", tier: 4 }, { name: "Agências digitais", tier: 4 },
  { name: "Vendedores B2B", tier: 4 }, { name: "Recursos Humanos", tier: 4 }, { name: "Empresas locais", tier: 4 },
  { name: "Universidades", tier: 4 }, { name: "Candidatos a bolsas", tier: 4 }, { name: "Trabalhadores informais", tier: 4 },
  { name: "Microempresários", tier: 4 }, { name: "Jovens profissionais", tier: 4 }, { name: "Líderes de equipas", tier: 4 },
  { name: "Assistentes administrativos", tier: 4 }, { name: "Secretárias", tier: 4 }, { name: "Donos de imóveis", tier: 4 },
  { name: "Inquilinos", tier: 4 }, { name: "Exportadores", tier: 4 }, { name: "Importadores", tier: 4 },
  { name: "Cooperativas agrícolas", tier: 4 }, { name: "Centros de formação", tier: 4 }, { name: "Criadores de newsletters", tier: 4 },
  { name: "Influenciadores iniciantes", tier: 4 }, { name: "Pessoas procrastinadoras", tier: 4 }, { name: "Pessoas sem objetivos", tier: 4 },
  { name: "Pessoas com dívidas", tier: 4 }, { name: "Pessoas sem poupança", tier: 4 }, { name: "Jovens investidores", tier: 4 },
  { name: "Pessoas criativas", tier: 4 }, { name: "Inventores", tier: 4 }, { name: "Empreendedores de IA", tier: 4 },
  { name: "Utilizadores de IA", tier: 4 },
  // Tier 5
  { name: "Criadores de Conteúdo (Influencers)", tier: 5 }, { name: "Agências de Marketing de Performance", tier: 5 }, { name: "Produtores de Festivais de Música", tier: 5 },
  { name: "Youtubers e Streamers Profissionais", tier: 5 }, { name: "Infoprodutores High-Ticket", tier: 5 }, { name: "Startups em Early Stage", tier: 5 },
  { name: "Redes de Podcasts", tier: 5 }, { name: "Agências de Lançamento de Infoprodutos", tier: 5 }, { name: "Consultores de Inteligência Artificial", tier: 5 },
  { name: "E-commerces DNVB (Direct-to-Consumer)", tier: 5 }, { name: "Especialistas em SEO e Growth Hacking", tier: 5 }, { name: "Gestores de Comunidades Onlines", tier: 5 },
  { name: "Copywriters de Resposta Direta", tier: 5 }, { name: "Editores de Vídeo de Alta Retenção", tier: 5 }, { name: "Plataformas de SaaS B2B Básico", tier: 5 },
  { name: "Fintechs em Estágio de Crescimento", tier: 5 }, { name: "EdTechs (Plataformas Educacionais)", tier: 5 }, { name: "Assistente financeiro com IA", tier: 5 },
  { name: "Rede social de desafios com IA", tier: 5 }, { name: "Criador de vídeos virais", tier: 5 }, { name: "Rede de networking baseada em IA", tier: 5 },
  { name: "Plataforma de criação de conteúdo com IA", tier: 5 }, { name: "Simulador de entrevistas com IA", tier: 5 }, { name: "Consultor de estilo IA", tier: 5 },
  { name: "Histórias infantis com IA", tier: 5 },
  // Tier 6
  { name: "Clínicas Psiquiátricas com Psicodélicos", tier: 6 }, { name: "Estúdios de Tatuagem Realista", tier: 6 }, { name: "Mecânicos Especializados em Porsches", tier: 6 },
  { name: "Criadores de Gado de Elite", tier: 6 }, { name: "Mergulhadores Profissionais de Alto Mar", tier: 6 }, { name: "Produtores de Cogumelos Exóticos", tier: 6 },
  { name: "Estúdios de Animação 3D para Games", tier: 6 }, { name: "Empresas de Instalação de Energia Solar", tier: 6 }, { name: "Fabricantes de Drones Agrícolas", tier: 6 },
  { name: "Laboratórios de Genética Pessoal", tier: 6 }, { name: "Cervejarias Ciganas (Sem Fábrica)", tier: 6 }, { name: "Apicultores de Mel Medicinal", tier: 6 },
  { name: "Fazendas de Mineração de Criptomoedas", tier: 6 }, { name: "Empresas de Desinfecção Hospitalar", tier: 6 }, { name: "Laboratórios de Biotecnologia", tier: 6 },
  { name: "Restauradores de Obras de Arte Clássicas", tier: 6 }, { name: "Investigadores Particulares Cibernéticos", tier: 6 }, { name: "Produtores de Cannabis Medicinal Legalizada", tier: 6 },
  { name: "Criadores de Avestruz e Carnes Exóticas", tier: 6 }, { name: "Operadores de Usinas Eólicas", tier: 6 }, { name: "Cultivadores de Trufas Brancas", tier: 6 },
  { name: "Pilotos de Balão Turístico", tier: 6 }
];
 
export const problems: Item[] = [
  // Tier 1
  { name: "Criação de Conteúdo para Redes", tier: 1 }, { name: "Organização de Estoque Físico", tier: 1 }, { name: "Controle de Ponto de Funcionários", tier: 1 },
  { name: "Emissão de Recibos em Papel", tier: 1 }, { name: "Agendamento Manual via Telefone", tier: 1 }, { name: "Perda de Clientes Frequentes", tier: 1 },
  { name: "Dificuldade de Controle de Caixa Diário", tier: 1 }, { name: "Fila de Espera Demorada e Desorganizada", tier: 1 }, { name: "Falta de Orçamentos Claros para o Cliente", tier: 1 },
  { name: "Controle de 'Fiados' e Cadernetas", tier: 1 }, { name: "Má Gestão de Entregas (Delivery)", tier: 1 }, { name: "Desafio de acordar cedo", tier: 1 },
  { name: "Diário de evolução", tier: 1 }, { name: "Clube da leitura diária", tier: 1 }, { name: "Diário de gratidão", tier: 1 },
  { name: "Receitas rápidas", tier: 1 },
  // Tier 2
  { name: "Agendamento e No-Shows (Faltas)", tier: 2 }, { name: "Gestão Financeira e Cobranças de Boletos", tier: 2 }, { name: "Emissão de Notas Fiscais Eletrônicas", tier: 2 },
  { name: "Atraso Constante em Pagamentos Mensais", tier: 2 }, { name: "Gestão de Frota de Veículos", tier: 2 }, { name: "Falta de Histórico Unificado de Clientes", tier: 2 },
  { name: "Dificuldade em Delegar Tarefas Simples", tier: 2 }, { name: "Compras de Insumos Desorganizadas", tier: 2 }, { name: "Cotação Lenta com Múltiplos Fornecedores", tier: 2 },
  { name: "Acompanhamento Cego de Pedidos", tier: 2 }, { name: "Logística Reversa e Gestão de Devoluções", tier: 2 }, { name: "Clube dos 30 dias", tier: 2 },
  { name: "Construção de hábitos", tier: 2 }, { name: "Metas compartilhadas", tier: 2 }, { name: "Ranking de disciplina", tier: 2 },
  { name: "Planejador de vida", tier: 2 }, { name: "Desafio sem redes sociais", tier: 2 }, { name: "Desafio de foco", tier: 2 },
  { name: "Networking local", tier: 2 }, { name: "Batalha de currículos", tier: 2 }, { name: "Construção de portfólio", tier: 2 },
  { name: "Diário de viagens", tier: 2 }, { name: "Descubra sua cidade", tier: 2 }, { name: "Aventuras locais", tier: 2 },
  { name: "Viagens econômicas", tier: 2 }, { name: "Receitas em vídeo", tier: 2 }, { name: "Ranking de receitas", tier: 2 },
  { name: "Refeições econômicas", tier: 2 }, { name: "Planejador alimentar", tier: 2 }, { name: "Receitas de família", tier: 2 },
  { name: "Troca de receitas", tier: 2 }, { name: "Atividades para crianças", tier: 2 }, { name: "Planejador familiar", tier: 2 },
  { name: "Diário da família", tier: 2 }, { name: "Aprender brincando", tier: 2 }, { name: "Futebol entre amigos", tier: 2 },
  { name: "Basquete local", tier: 2 }, { name: "Treinos esportivos", tier: 2 }, { name: "Estatísticas pessoais", tier: 2 },
  { name: "Jogos recreativos", tier: 2 }, { name: "Troca de roupas", tier: 2 }, { name: "Looks do dia", tier: 2 },
  { name: "Dicas de maquiagem", tier: 2 }, { name: "Estilo masculino", tier: 2 }, { name: "Estilo feminino", tier: 2 },
  // Tier 3
  { name: "Recrutamento e Seleção de Talentos Base", tier: 3 }, { name: "Otimização de SEO Local (Google Maps)", tier: 3 }, { name: "Treinamento de Equipe Operacional", tier: 3 },
  { name: "Organização de Documentos na Nuvem", tier: 3 }, { name: "Gestão de Tarefas Complexas em Equipe", tier: 3 }, { name: "Controle de Prazos de Entregas B2B", tier: 3 },
  { name: "Conformidade Trabalhista e Ponto Digital", tier: 3 }, { name: "Criação Rápida de Propostas Comerciais Visuais", tier: 3 }, { name: "Onboarding Confuso de Novos Funcionários", tier: 3 },
  { name: "Desafio sem procrastinação", tier: 3 }, { name: "Competição de produtividade", tier: 3 }, { name: "Missões de autodesenvolvimento", tier: 3 },
  { name: "Sistema de recompensas pessoais", tier: 3 }, { name: "Clube dos vencedores", tier: 3 }, { name: "Missões de coragem", tier: 3 },
  { name: "Desafios de habilidades profissionais", tier: 3 }, { name: "Ranking de freelancers", tier: 3 }, { name: "Banco de talentos", tier: 3 },
  { name: "Missões para carreira", tier: 3 }, { name: "Aprender vendas", tier: 3 }, { name: "Aprender negociação", tier: 3 },
  { name: "Avaliação profissional", tier: 3 }, { name: "Coaching profissional", tier: 3 }, { name: "Ranking de especialistas", tier: 3 },
  { name: "Caça a lugares secretos", tier: 3 }, { name: "Desafios de viagem", tier: 3 }, { name: "Ranking de exploradores", tier: 3 },
  { name: "Turismo colaborativo", tier: 3 }, { name: "Turismo gastronômico", tier: 3 }, { name: "Guia feito pelos usuários", tier: 3 },
  { name: "Check-in gamificado", tier: 3 }, { name: "Mochileiros conectados", tier: 3 }, { name: "Turismo histórico", tier: 3 },
  { name: "Trilhas compartilhadas", tier: 3 }, { name: "Fotos de lugares raros", tier: 3 }, { name: "Ranking de destinos", tier: 3 },
  { name: "Viagens em grupo", tier: 3 }, { name: "Mapa de experiências", tier: 3 }, { name: "Desafio culinário diário", tier: 3 },
  { name: "Comunidade vegana", tier: 3 }, { name: "Desafio de alimentação saudável", tier: 3 }, { name: "Comunidade fitness culinária", tier: 3 },
  { name: "Comida internacional", tier: 3 }, { name: "Concurso gastronômico", tier: 3 }, { name: "Ranking de restaurantes", tier: 3 },
  { name: "Marmitas inteligentes", tier: 3 }, { name: "Cozinha colaborativa", tier: 3 }, { name: "Jogos educativos familiares", tier: 3 },
  { name: "Clube da família", tier: 3 }, { name: "Missões familiares", tier: 3 }, { name: "Aprendizagem divertida", tier: 3 },
  { name: "Desafios entre pais e filhos", tier: 3 }, { name: "Rede de pais", tier: 3 }, { name: "Comunidade escolar", tier: 3 },
  { name: "Recompensas infantis", tier: 3 }, { name: "Aventuras educativas", tier: 3 }, { name: "Clube dos pequenos leitores", tier: 3 },
  { name: "Matemática infantil", tier: 3 }, { name: "Desafios criativos infantis", tier: 3 }, { name: "Histórias colaborativas", tier: 3 },
  { name: "Clube de talentos infantis", tier: 3 }, { name: "Karaokê competitivo", tier: 3 }, { name: "Letras colaborativas", tier: 3 },
  { name: "Ranking musical", tier: 3 }, { name: "Treino vocal", tier: 3 }, { name: "Desafios musicais", tier: 3 },
  { name: "Aprender instrumentos", tier: 3 }, { name: "Música por localização", tier: 3 }, { name: "Ranking de artistas locais", tier: 3 },
  { name: "Liga de futebol amador", tier: 3 }, { name: "Ranking de jogadores locais", tier: 3 }, { name: "Comunidade de corrida", tier: 3 },
  { name: "Desafios esportivos", tier: 3 }, { name: "Clube de ciclismo", tier: 3 }, { name: "Torneios comunitários", tier: 3 },
  { name: "Clube de atletas", tier: 3 }, { name: "Missões esportivas", tier: 3 }, { name: "Ranking regional", tier: 3 },
  { name: "Desafios de resistência", tier: 3 }, { name: "Eventos esportivos", tier: 3 }, { name: "Equipes por bairro", tier: 3 },
  { name: "Avaliação de looks", tier: 3 }, { name: "Comunidade fashion", tier: 3 }, { name: "Desafio de moda", tier: 3 },
  { name: "Ranking de estilo", tier: 3 }, { name: "Armário digital", tier: 3 }, { name: "Moda sustentável", tier: 3 },
  { name: "Tendências locais", tier: 3 }, { name: "Beleza colaborativa", tier: 3 }, { name: "Moda para eventos", tier: 3 },
  { name: "Concurso fashion", tier: 3 }, { name: "Desafios ecológicos", tier: 3 }, { name: "Plantio colaborativo", tier: 3 },
  { name: "Comunidade verde", tier: 3 }, { name: "Ranking ecológico", tier: 3 }, { name: "Missões sustentáveis", tier: 3 },
  { name: "Limpeza comunitária", tier: 3 }, { name: "Clube ambiental", tier: 3 }, { name: "Monitor de consumo", tier: 3 },
  { name: "Horta coletiva", tier: 3 }, { name: "Sustentabilidade doméstica", tier: 3 }, { name: "Economia circular", tier: 3 },
  { name: "Troca sustentável", tier: 3 }, { name: "Educação ambiental", tier: 3 }, { name: "Voluntariado verde", tier: 3 },
  { name: "Eventos ecológicos", tier: 3 }, { name: "Concurso ambiental", tier: 3 }, { name: "Comunidade de recicladores", tier: 3 },
  { name: "Impacto positivo", tier: 3 }, { name: "Banco de ideias", tier: 3 }, { name: "Clube dos curiosos", tier: 3 },
  { name: "Caça a oportunidades", tier: 3 }, { name: "Preparação para exames nacionais", tier: 3 }, { name: "Explicações escolares por IA", tier: 3 },
  { name: "Aprender inglês para emprego", tier: 3 }, { name: "Gestão de pequenos comércios", tier: 3 }, { name: "Gestão de cantinas escolares", tier: 3 },
  { name: "Gestão de mototáxis", tier: 3 }, { name: "Gestão de táxis", tier: 3 }, { name: "Gestão de igrejas", tier: 3 },
  { name: "Gestão de associações", tier: 3 }, { name: "Gestão de cooperativas", tier: 3 }, { name: "Marketplace de explicadores", tier: 3 },
  { name: "Marketplace de serviços locais", tier: 3 }, { name: "Marketplace de freelancers africanos", tier: 3 }, { name: "Rede profissional africana", tier: 3 },
  { name: "Rede de estudantes africanos", tier: 3 }, { name: "Aplicação de bolsas de estudo", tier: 3 }, { name: "Aplicação de oportunidades de emprego", tier: 3 },
  { name: "Aplicação de concursos públicos", tier: 3 }, { name: "Aplicação de financiamento para negócios", tier: 3 }, { name: "Aplicação de educação financeira", tier: 3 },
  { name: "Aprender inglês", tier: 3 }, { name: "Perder peso", tier: 3 }, { name: "Ganhar dinheiro online", tier: 3 },
  { name: "Encontrar emprego", tier: 3 }, { name: "Criar conteúdo", tier: 3 }, { name: "Aprender programação", tier: 3 },
  { name: "Investir dinheiro", tier: 3 }, { name: "Melhorar produtividade", tier: 3 }, { name: "Desenvolver hábitos", tier: 3 },
  { name: "Saúde mental", tier: 3 }, { name: "Gestão financeira", tier: 3 }, { name: "Preparação para exames", tier: 3 },
  { name: "Gestão de pequenos negócios", tier: 3 }, { name: "Procura de clientes", tier: 3 }, { name: "Networking profissional", tier: 3 },
  { name: "Aprendizagem de IA", tier: 3 }, { name: "Trabalho remoto", tier: 3 }, { name: "Educação infantil", tier: 3 },
  { name: "Gestão familiar", tier: 3 }, { name: "Organização pessoal", tier: 3 }, { name: "Planeamento do dia", tier: 3 },
  { name: "Gestão de tarefas", tier: 3 }, { name: "Lista de compras", tier: 3 }, { name: "Controle financeiro", tier: 3 },
  { name: "Controle de hábitos", tier: 3 }, { name: "Exercícios rápidos", tier: 3 }, { name: "Aprender palavras novas", tier: 3 },
  { name: "Diário pessoal", tier: 3 }, { name: "Meditação", tier: 3 }, { name: "Planeamento alimentar", tier: 3 },
  { name: "Gestão de estudos", tier: 3 }, { name: "Controle de metas", tier: 3 }, { name: "Monitoramento de sono", tier: 3 },
  { name: "Organização doméstica", tier: 3 }, { name: "Agenda familiar", tier: 3 }, { name: "Controle de medicamentos", tier: 3 },
  { name: "Gestão de documentos", tier: 3 }, { name: "Controle de consumo de água", tier: 3 }, { name: "Gestão de contactos", tier: 3 },
  { name: "Planeamento semanal", tier: 3 }, { name: "Gestão de clientes", tier: 3 }, { name: "CRM para microempresas", tier: 3 },
  { name: "Gestão de vendas", tier: 3 }, { name: "Gestão escolar", tier: 3 }, { name: "Gestão de clínicas", tier: 3 },
  { name: "Gestão de oficinas", tier: 3 }, { name: "Gestão de restaurantes", tier: 3 }, { name: "Gestão de imobiliárias", tier: 3 },
  { name: "Gestão de academias", tier: 3 }, { name: "Gestão de recursos humanos", tier: 3 }, { name: "Gestão de projetos", tier: 3 },
  { name: "Gestão de contratos", tier: 3 }, { name: "Gestão financeira empresarial", tier: 3 }, { name: "Automação de marketing", tier: 3 },
  { name: "Automação de WhatsApp", tier: 3 }, { name: "Atendimento por IA", tier: 3 }, { name: "Agentes de vendas IA", tier: 3 },
  { name: "Geração de leads", tier: 3 }, { name: "Inteligência comercial", tier: 3 }, { name: "Ganhar dinheiro", tier: 3 },
  { name: "Poupar dinheiro", tier: 3 }, { name: "Encontrar clientes", tier: 3 }, { name: "Aprender mais rápido", tier: 3 },
  { name: "Organizar a vida", tier: 3 }, { name: "Encontrar parceiros", tier: 3 }, { name: "Melhorar a saúde", tier: 3 },
  { name: "Melhorar aparência", tier: 3 }, { name: "Criar riqueza", tier: 3 }, { name: "Ter disciplina", tier: 3 },
  { name: "Combater procrastinação", tier: 3 }, { name: "Reduzir ansiedade", tier: 3 }, { name: "Dormir melhor", tier: 3 },
  { name: "Ser mais produtivo", tier: 3 }, { name: "Educar filhos", tier: 3 }, { name: "Desenvolver carreira", tier: 3 },
  { name: "Comunicar melhor", tier: 3 }, { name: "Fazer amigos", tier: 3 }, { name: "Construir negócios", tier: 3 },
  { name: "Como sobreviver até ao próximo salário", tier: 3 }, { name: "Controle de gastos em tempo real", tier: 3 }, { name: "Divisão automática de despesas familiares", tier: 3 },
  { name: "Gestão financeira para casais", tier: 3 }, { name: "Planeamento de aposentadoria", tier: 3 }, { name: "Simulador de enriquecimento", tier: 3 },
  { name: "Detector de desperdícios financeiros", tier: 3 }, { name: "Assistente de compras inteligente", tier: 3 }, { name: "Comparador automático de preços", tier: 3 },
  { name: "Assistente para negociação de dívidas", tier: 3 }, { name: "Encontrar emprego automaticamente", tier: 3 }, { name: "Preparação para entrevistas", tier: 3 },
  { name: "Simulação de entrevistas com IA", tier: 3 }, { name: "Criação automática de CV", tier: 3 }, { name: "Otimização de LinkedIn", tier: 3 },
  { name: "Planeamento de carreira", tier: 3 }, { name: "Descoberta de profissões", tier: 3 }, { name: "Mudança de carreira", tier: 3 },
  { name: "Freelancing global", tier: 3 }, { name: "Gestão de stock simplificada", tier: 3 }, { name: "Sistema de cobranças", tier: 3 },
  { name: "Emissão de faturas", tier: 3 }, { name: "Gestão de fornecedores", tier: 3 }, { name: "Planeamento empresarial", tier: 3 },
  { name: "Emprego", tier: 3 }, { name: "Educação", tier: 3 }, { name: "Saúde", tier: 3 },
  { name: "Finanças", tier: 3 }, { name: "Habitação", tier: 3 }, { name: "Alimentação", tier: 3 },
  { name: "Transporte", tier: 3 }, { name: "Comunicação", tier: 3 }, { name: "Entretenimento", tier: 3 },
  { name: "Segurança", tier: 3 }, { name: "Energia", tier: 3 }, { name: "Água", tier: 3 },
  { name: "Agricultura", tier: 3 }, { name: "Comércio", tier: 3 }, { name: "Logística", tier: 3 },
  { name: "Turismo", tier: 3 }, { name: "Recursos humanos", tier: 3 }, { name: "Marketing", tier: 3 },
  { name: "Software empresarial", tier: 3 }, { name: "Inteligência artificial", tier: 3 }, { name: "Gestão de escolas privadas", tier: 3 },
  { name: "Gestão de centros de formação", tier: 3 }, { name: "Gestão de explicadores", tier: 3 }, { name: "Gestão de pequenas clínicas", tier: 3 },
  { name: "Gestão de farmácias", tier: 3 }, { name: "Marketplace de empregos locais", tier: 3 }, { name: "Marketplace de profissionais técnicos", tier: 3 },
  { name: "Marketplace de artesãos", tier: 3 }, { name: "Marketplace de agricultores", tier: 3 }, { name: "Marketplace de serviços domésticos", tier: 3 },
  { name: "Plataforma de bolsas de estudo", tier: 3 }, { name: "Plataforma de formação profissional", tier: 3 }, { name: "Plataforma de estágios", tier: 3 },
  { name: "Organização da vida pessoal", tier: 3 }, { name: "Comunidade de estudantes", tier: 3 }, { name: "Comunidade de empreendedores", tier: 3 },
  { name: "Comunidade de investidores", tier: 3 }, { name: "Comunidade fitness", tier: 3 }, { name: "Comunidade de criadores", tier: 3 },
  { name: "Comunidade de freelancers", tier: 3 }, { name: "Comunidade de gamers", tier: 3 }, { name: "Comunidade de mães", tier: 3 },
  { name: "Comunidade de profissionais", tier: 3 }, { name: "Dificuldade em estudar", tier: 3 }, { name: "Falta de organização", tier: 3 },
  { name: "Excesso de informação", tier: 3 }, { name: "Dificuldade de aprendizagem", tier: 3 }, { name: "Falta de tempo", tier: 3 },
  { name: "Excesso de tarefas", tier: 3 }, { name: "Falta de clientes", tier: 3 }, { name: "Gestão ineficiente", tier: 3 },
  { name: "Pouca visibilidade", tier: 3 }, { name: "Alta concorrência", tier: 3 }, { name: "Trabalho repetitivo", tier: 3 },
  { name: "Dificuldade em usar IA", tier: 3 }, { name: "Processos manuais", tier: 3 }, { name: "Falta de reputação", tier: 3 },
  { name: "Baixo engajamento", tier: 3 }, { name: "Baixo alcance", tier: 3 }, { name: "Falta de diferenciação", tier: 3 },
  { name: "Baixa retenção", tier: 3 }, { name: "Pouca audiência", tier: 3 }, { name: "Falta de tráfego", tier: 3 },
  { name: "Falta de dados", tier: 3 }, { name: "Dificuldade em vender", tier: 3 }, { name: "Poucos contactos", tier: 3 },
  { name: "Falta de escala", tier: 3 }, { name: "Falta de autoridade", tier: 3 }, { name: "Falta de crescimento", tier: 3 },
  { name: "Falta de investidores", tier: 3 }, { name: "Solidão", tier: 3 }, { name: "Falta de oportunidades", tier: 3 },
  { name: "Gestão de stock", tier: 3 }, { name: "Custos elevados", tier: 3 }, { name: "Baixas vendas", tier: 3 },
  { name: "Falta de previsões", tier: 3 }, { name: "Gestão logística", tier: 3 }, { name: "Desorganização financeira", tier: 3 },
  { name: "Falta de visibilidade", tier: 3 }, { name: "Estresse", tier: 3 }, { name: "Falta de qualificação", tier: 3 },
  { name: "Falta de acompanhamento", tier: 3 }, { name: "Falta de conhecimento", tier: 3 }, { name: "Falta de apoio", tier: 3 },
  { name: "Falta de acompanhamento médico", tier: 3 }, { name: "Falta de experiência", tier: 3 }, { name: "Falta de orientação", tier: 3 },
  { name: "Falta de análise", tier: 3 }, { name: "Excesso de opções", tier: 3 }, { name: "Falta de conversão", tier: 3 },
  { name: "Falta de progressão", tier: 3 }, { name: "Falta de disciplina", tier: 3 }, { name: "Falta de planeamento", tier: 3 },
  { name: "Falta de consistência", tier: 3 }, { name: "Má alimentação", tier: 3 }, { name: "Falta de prática", tier: 3 },
  { name: "Comunicação ruim", tier: 3 }, { name: "Falta de networking", tier: 3 }, { name: "Gestão de comunidade", tier: 3 },
  { name: "Falta de método de estudo", tier: 3 }, { name: "Triagem manual de currículos", tier: 3 }, { name: "Atendimento lento", tier: 3 },
  { name: "Abandono de carrinho", tier: 3 }, { name: "Falta de portfólio", tier: 3 }, { name: "Comunicação dispersa", tier: 3 },
  { name: "Registos em papel", tier: 3 }, { name: "Gestão de marcações", tier: 3 }, { name: "Faltas de pacientes", tier: 3 },
  { name: "Falta de alunos", tier: 3 }, { name: "Falta de estágio", tier: 3 }, { name: "Produção lenta", tier: 3 },
  { name: "Falta de ideias", tier: 3 }, { name: "Crescimento lento", tier: 3 }, { name: "Baixa conversão", tier: 3 },
  { name: "Desperdício alimentar", tier: 3 }, { name: "Preços imprevisíveis", tier: 3 }, { name: "Falta de mercado", tier: 3 },
  { name: "Rotas ineficientes", tier: 3 }, { name: "Ganhos variáveis", tier: 3 }, { name: "Falta de gestão financeira", tier: 3 },
  { name: "Sobrecarga diária", tier: 3 }, { name: "Planeamento financeiro", tier: 3 }, { name: "Falta de conexões", tier: 3 },
  { name: "Falta de integração", tier: 3 }, { name: "Isolamento", tier: 3 }, { name: "Falta de comunidade", tier: 3 },
  { name: "Medo de investir", tier: 3 }, { name: "Falta de leads", tier: 3 }, { name: "Tarefas repetitivas", tier: 3 },
  { name: "Gestão manual", tier: 3 }, { name: "Acompanhamento difícil", tier: 3 }, { name: "Escalabilidade limitada", tier: 3 },
  { name: "Falta de suporte diário", tier: 3 }, { name: "Maus hábitos de sono", tier: 3 }, { name: "Falta de motivação", tier: 3 },
  { name: "Dificuldade em emagrecer", tier: 3 }, { name: "Falta de conversação", tier: 3 }, { name: "Curva de aprendizagem", tier: 3 },
  { name: "Gestão de membros", tier: 3 }, { name: "Falta de doadores", tier: 3 }, { name: "Falta de previsibilidade", tier: 3 },
  { name: "Escala limitada", tier: 3 }, { name: "Dependência de sessões", tier: 3 }, { name: "Procura irregular", tier: 3 },
  { name: "Pouca exposição", tier: 3 }, { name: "Falta de vendas", tier: 3 }, { name: "Falta de mentoria", tier: 3 },
  { name: "Falta de validação", tier: 3 }, { name: "Ciclos longos", tier: 3 }, { name: "Falta de candidatos", tier: 3 },
  { name: "Pouca presença online", tier: 3 }, { name: "Desistência de alunos", tier: 3 }, { name: "Evasão escolar", tier: 3 },
  { name: "Informação dispersa", tier: 3 }, { name: "Processos complexos", tier: 3 }, { name: "Falta de registos", tier: 3 },
  { name: "Gestão de caixa", tier: 3 }, { name: "Falta de métricas", tier: 3 }, { name: "Baixo desempenho", tier: 3 },
  { name: "Excesso de reuniões", tier: 3 }, { name: "Gestão de agenda", tier: 3 }, { name: "Gestão de arrendamentos", tier: 3 },
  { name: "Procura demorada", tier: 3 }, { name: "Falta de informação", tier: 3 }, { name: "Falta de contactos", tier: 3 },
  { name: "Falta de fornecedores", tier: 3 }, { name: "Gestão dispersa", tier: 3 }, { name: "Descoberta limitada", tier: 3 },
  { name: "Falta de estratégia", tier: 3 }, { name: "Falta de execução", tier: 3 }, { name: "Falta de direção", tier: 3 },
  { name: "Má gestão financeira", tier: 3 }, { name: "Gastos excessivos", tier: 3 }, { name: "Ideias desorganizadas", tier: 3 },
  { name: "Excesso de ferramentas", tier: 3 },
  // Tier 4
  { name: "Retenção de Clientes Premium VIPs", tier: 4 }, { name: "Gestão de Contratos e Assinaturas Digitais", tier: 4 }, { name: "Coleta Automática de Feedbacks e Avaliações", tier: 4 },
  { name: "Controle de Garantias de Produtos Caros", tier: 4 }, { name: "Previsão de Demanda de Estoque para o Trimestre", tier: 4 }, { name: "Cálculo Preciso de Margem de Lucro por Projeto", tier: 4 },
  { name: "Automação de Marketing B2B Omnichannel", tier: 4 }, { name: "Integração Pobre com Sistemas Legados Antigos", tier: 4 }, { name: "Gestão de Riscos Operacionais em Escala", tier: 4 },
  { name: "Compliance Fiscal e Tributário Dinâmico", tier: 4 }, { name: "Academia mental", tier: 4 }, { name: "Evolução pessoal gamificada", tier: 4 },
  { name: "Simulador de entrevistas com IA", tier: 4 }, { name: "Clube de empreendedores", tier: 4 }, { name: "Comunidade de startups", tier: 4 },
  { name: "Comunidade de programadores", tier: 4 }, { name: "Clube de líderes", tier: 4 }, { name: "Marketplace de conhecimento", tier: 4 },
  { name: "Carreira internacional", tier: 4 }, { name: "Passaporte digital de viagens", tier: 4 }, { name: "Competição entre viajantes", tier: 4 },
  { name: "Batalha de cozinheiros", tier: 4 }, { name: "Cardápio inteligente", tier: 4 }, { name: "Clube dos chefs", tier: 4 },
  { name: "Educação gamificada", tier: 4 }, { name: "Batalha de cantores", tier: 4 }, { name: "Liga de músicos", tier: 4 },
  { name: "Concurso de composição", tier: 4 }, { name: "Descoberta de talentos", tier: 4 }, { name: "Banda virtual", tier: 4 },
  { name: "Jam sessions online", tier: 4 }, { name: "Comunidade de DJs", tier: 4 }, { name: "Remix colaborativo", tier: 4 },
  { name: "Clube de compositores", tier: 4 }, { name: "Produção musical social", tier: 4 }, { name: "Festival virtual", tier: 4 },
  { name: "Scout de talentos", tier: 4 }, { name: "Fantasy esportivo local", tier: 4 }, { name: "Comunidade de esportes radicais", tier: 4 },
  { name: "Simulador de cortes de cabelo", tier: 4 }, { name: "Comunidade de influenciadores", tier: 4 }, { name: "Fashion battle", tier: 4 },
  { name: "Reciclagem gamificada", tier: 4 }, { name: "Redução de carbono", tier: 4 }, { name: "Reality show entre usuários", tier: 4 },
  { name: "Competição de inteligência", tier: 4 }, { name: "Simulador de fama", tier: 4 }, { name: "Missões secretas", tier: 4 },
  { name: "Rede de desafios globais", tier: 4 }, { name: "Campeonato de criatividade", tier: 4 }, { name: "Liga de solucionadores de problemas", tier: 4 },
  { name: "Rede de inventores", tier: 4 }, { name: "Construção coletiva de projetos", tier: 4 }, { name: "Ranking de inovação", tier: 4 },
  { name: "Rede de descobertas", tier: 4 }, { name: "Competição de startups", tier: 4 }, { name: "Comunidade de visionários", tier: 4 },
  { name: "Missões empresariais", tier: 4 }, { name: "Liga dos criadores", tier: 4 }, { name: "Top 20 mais promissoras entre as 400 ideias", tier: 4 },
  { name: "Reality show digital", tier: 4 }, { name: "Competições de criatividade", tier: 4 }, { name: "Simulador de entrevistas com IA", tier: 4 },
  { name: "Aprendizagem gamificada de idiomas", tier: 4 }, { name: "Fitness com rankings sociais", tier: 4 }, { name: "Marketplace hiperlocal", tier: 4 },
  { name: "Banco de ideias monetizáveis", tier: 4 }, { name: "Clube dos empreendedores", tier: 4 }, { name: "Passaporte digital de viagens", tier: 4 },
  { name: "Liga de músicos", tier: 4 }, { name: "Fantasy esportivo local", tier: 4 }, { name: "Fashion battle", tier: 4 },
  { name: "Detector de tendências", tier: 4 }, { name: "Comunidade de startups", tier: 4 }, { name: "Campeonato global de habilidades", tier: 4 },
  { name: "Ecossistema de missões e recompensas", tier: 4 },
  // Tier 5
  { name: "Aquisição Cara de Leads Frios via Anúncios", tier: 5 }, { name: "Baixo Engajamento e Cultura de Funcionários Remotos", tier: 5 }, { name: "Onboarding Dinâmico e Gamificado de Clientes", tier: 5 },
  { name: "Personalização em Massa de Emails (Cold Emailing)", tier: 5 }, { name: "Automação Inteligente de Funil de Vendas", tier: 5 }, { name: "Monitoramento Cego de Métricas SaaS (LTV/CAC)", tier: 5 },
  { name: "Gestão Descentralizada de Afiliados e Parceiros", tier: 5 }, { name: "Otimização Contínua de Conversão (CRO) de LPs", tier: 5 }, { name: "Segmentação de Audiência Super Avançada", tier: 5 },
  { name: "Qualificação Automática de Leads via Comportamento", tier: 5 }, { name: "Coach de hábitos por IA", tier: 5 }, { name: "Mentor IA", tier: 5 },
  { name: "Pratos criados por IA", tier: 5 }, { name: "Histórias infantis com IA", tier: 5 }, { name: "Criador de músicas IA", tier: 5 },
  { name: "Consultor de estilo IA", tier: 5 }, { name: "Personal shopper IA", tier: 5 }, { name: "IA para prever tendências", tier: 5 },
  { name: "Ecossistema global de desafios", tier: 5 }, { name: "Rede social de desafios IA", tier: 5 }, { name: "Consultor de estilo IA", tier: 5 },
  { name: "Histórias infantis com IA", tier: 5 },
  // Tier 6
  { name: "Prevenção Avançada de Fraudes com Cartão Clonado", tier: 6 }, { name: "Monitoramento Deep Web de Reputação Online", tier: 6 }, { name: "Tradução e Localização Contextual em Tempo Real", tier: 6 },
  { name: "Logística e Otimização de Rotas de Múltiplos Veículos", tier: 6 }, { name: "Automação de Respostas de Suporte de Alta Complexidade", tier: 6 }, { name: "Rastreio Global de Ativos Extremamente Valiosos", tier: 6 },
  { name: "Análise Preditiva de Churn (Cancelamento) de Contas Key", tier: 6 }, { name: "Detecção de Anomalias Financeiras e Lavagem de Dinheiro", tier: 6 }, { name: "Simulação de Cenários de Crise em Realidade Virtual", tier: 6 },
  { name: "Auditoria Imutável de Contratos e Acordos em Blockchain", tier: 6 }, { name: "Gestão Automatizada de Créditos de Carbono ESG", tier: 6 }
];
 
export const technologies: Item[] = [
  // Tier 1
  { name: "Painéis de Business Intelligence Básicos", tier: 1 }, { name: "CRM Simplificado", tier: 1 }, { name: "Aplicativo Mobile Responsivo PWA", tier: 1 },
  { name: "Construtor de Landing Pages Dinâmicas", tier: 1 }, { name: "Sistema PDV Operando na Nuvem", tier: 1 }, { name: "Gestor de Tarefas estilo Kanban", tier: 1 },
  { name: "Extensão Utilitária para Google Chrome", tier: 1 }, { name: "Sincronização com Planilhas Automatizadas", tier: 1 }, { name: "Criador de Formulários com Condicionais", tier: 1 },
  // Tier 2
  { name: "Integração Transparente via APIs REST", tier: 2 }, { name: "Portais de Cliente Totalmente White-label", tier: 2 }, { name: "Motor de Disparo de SMS/Emails Transacionais", tier: 2 },
  { name: "Gestor Granular de Permissões de Usuários", tier: 2 }, { name: "Sistema de Agendamento Online Self-Service", tier: 2 }, { name: "App de Delivery Whitelabel com Rastreio", tier: 2 },
  { name: "Catálogo Digital Interativo Escaneável", tier: 2 }, { name: "Sistema de Tickets de Suporte e Helpdesk", tier: 2 },
  // Tier 3
  { name: "Automações No-Code Complexas (Make/Zapier)", tier: 3 }, { name: "Dashboards Interativos Consolidados em Tempo Real", tier: 3 }, { name: "Reconhecimento de Voz Básico (Speech-to-Text)", tier: 3 },
  { name: "Web Scraping Automatizado Extraindo Dados Concorrentes", tier: 3 }, { name: "Integração Nativa com Múltiplos ERPs (SAP/Totvs)", tier: 3 }, { name: "Motores de Busca Internos Inteligentes (Elasticsearch)", tier: 3 },
  { name: "Sistema de Assinatura Eletrônica e Criptografia", tier: 3 }, { name: "Gerador de Relatórios Dinâmicos Exportáveis (PDF/CSV)", tier: 3 },
  // Tier 4
  { name: "Chatbots de WhatsApp com Processamento Natural", tier: 4 }, { name: "Assistentes de Voz Especializados (Voice AI)", tier: 4 }, { name: "Integração Bidirecional com IoT (Internet das Coisas)", tier: 4 },
  { name: "Motor de Regras de Negócio Personalizável", tier: 4 }, { name: "Automação Gráfica de Fluxo de Trabalho (Workflow Engine)", tier: 4 }, { name: "Reconhecimento Ótico de Caracteres Avançado (OCR)", tier: 4 },
  { name: "Motor de Recomendação Algorítmica de Produtos", tier: 4 }, { name: "Tutor de exames nacionais angolanos com IA", tier: 4 }, { name: "Simulador de entrevistas para emprego em Angola", tier: 4 },
  { name: "Assistente financeiro para pequenos comerciantes africanos", tier: 4 }, { name: "Plataforma de explicadores para PALOP", tier: 4 }, { name: "Aplicação de inglês para profissionais africanos", tier: 4 },
  { name: "CRM para microempresas africanas", tier: 4 }, { name: "Gestão de mototáxis", tier: 4 }, { name: "Gestão de igrejas locais", tier: 4 },
  { name: "Planeador de carreira para estudantes africanos", tier: 4 }, { name: "Comunidade profissional africana baseada em competências", tier: 4 }, { name: "Tutor escolar com IA para PALOP", tier: 4 },
  { name: "Aplicação para aprender inglês focada em emprego", tier: 4 }, { name: "Gestor financeiro pessoal para mercados africanos", tier: 4 }, { name: "Assistente para pequenos comerciantes", tier: 4 },
  { name: "Plataforma de criação de conteúdo para TikTok, YouTube e Instagram com IA", tier: 4 }, { name: "Assistente pessoal com IA", tier: 4 }, { name: "Segunda mente com IA", tier: 4 },
  { name: "Coach de produtividade com IA", tier: 4 }, { name: "Gerenciador de vida com IA", tier: 4 }, { name: "Planeador de carreira com IA", tier: 4 },
  { name: "Tutor universal com IA", tier: 4 }, { name: "Agente financeiro pessoal", tier: 4 }, { name: "Agente de negócios pessoal", tier: 4 },
  { name: "Agente de aprendizagem", tier: 4 }, { name: "Agente de saúde preventiva", tier: 4 }, { name: "Gerador de vídeos virais", tier: 4 },
  { name: "Gerador de Shorts", tier: 4 }, { name: "Gerador de Reels", tier: 4 }, { name: "Criador automático de canais", tier: 4 },
  { name: "Editor de vídeo por IA", tier: 4 }, { name: "Gerador de thumbnails", tier: 4 }, { name: "Gerador de roteiros", tier: 4 },
  { name: "Gerador de posts", tier: 4 }, { name: "Gerador de podcasts", tier: 4 }, { name: "Clonagem de voz", tier: 4 },
  { name: "Gerador de negócios por IA", tier: 4 }, { name: "Marketplace de freelancers IA", tier: 4 }, { name: "Plataforma de microtarefas IA", tier: 4 },
  { name: "Sistema de renda extra", tier: 4 }, { name: "Descobridor de oportunidades", tier: 4 }, { name: "SaaS builder", tier: 4 },
  { name: "No-code builder", tier: 4 }, { name: "App builder por text", tier: 4 }, { name: "Marketplace de agentes IA", tier: 4 },
  { name: "Marketplace de prompts", tier: 4 }, { name: "Professor particular IA", tier: 4 }, { name: "Aplicação para exames", tier: 4 },
  { name: "Aprender inglês com IA", tier: 4 }, { name: "Aprender programação", tier: 4 }, { name: "Aprender matemática", tier: 4 },
  { name: "Aprender medicina", tier: 4 }, { name: "Aprender direito", tier: 4 }, { name: "Aprender vendas", tier: 4 },
  { name: "Aprender marketing", tier: 4 }, { name: "Aprender IA", tier: 4 }, { name: "Anti-procrastinação", tier: 4 },
  { name: "Criador de hábitos", tier: 4 }, { name: "Gestor de tarefas inteligente", tier: 4 }, { name: "Planeador de objetivos", tier: 4 },
  { name: "Organizador de rotina", tier: 4 }, { name: "Sistema de foco", tier: 4 }, { name: "Gestão de conhecimento", tier: 4 },
  { name: "Gestão de tempo", tier: 4 }, { name: "Gestão de projetos pessoais", tier: 4 }, { name: "Combate à ansiedade", tier: 4 },
  { name: "Combate ao estresse", tier: 4 }, { name: "Meditação personalizada", tier: 4 }, { name: "Terapia assistida por IA", tier: 4 },
  { name: "Diário emocional", tier: 4 }, { name: "Monitor de humor", tier: 4 }, { name: "Coach motivacional", tier: 4 },
  { name: "Saúde mental para estudantes", tier: 4 }, { name: "Saúde mental para empreendedores", tier: 4 }, { name: "Sono inteligente", tier: 4 },
  { name: "Emagrecimento inteligente", tier: 4 }, { name: "Nutrição personalizada", tier: 4 }, { name: "Treinos personalizados", tier: 4 },
  { name: "Contador de calorias IA", tier: 4 }, { name: "Coach fitness IA", tier: 4 }, { name: "Corrida inteligente", tier: 4 },
  { name: "Musculação inteligente", tier: 4 }, { name: "Yoga personalizada", tier: 4 }, { name: "Exercícios em casa", tier: 4 },
  { name: "Fitness gamificado", tier: 4 }, { name: "Planeamento financeiro", tier: 4 }, { name: "Controle de despesas", tier: 4 },
  { name: "Investimentos iniciantes", tier: 4 }, { name: "Gestão de dívidas", tier: 4 }, { name: "Poupança automática", tier: 4 },
  { name: "Orçamento familiar", tier: 4 }, { name: "Comparador de investimentos", tier: 4 }, { name: "Simulador financeiro", tier: 4 },
  { name: "Consultor financeiro IA", tier: 4 }, { name: "Compatibilidade de casais", tier: 4 }, { name: "Conselheiro de namoro", tier: 4 },
  { name: "Coach social", tier: 4 }, { name: "Comunicação para casais", tier: 4 }, { name: "Desenvolvimento pessoal", tier: 4 },
  { name: "Construção de amizades", tier: 4 }, { name: "Networking inteligente", tier: 4 }, { name: "Eventos sociais", tier: 4 },
  { name: "Comunidades privadas", tier: 4 }, { name: "Matchmaking por interesses", tier: 4 }, { name: "IA para agricultores africanos", tier: 4 },
  { name: "IA para pequenos comerciantes", tier: 4 }, { name: "IA para vendedores ambulantes", tier: 4 }, { name: "IA para estudantes africanos", tier: 4 },
  { name: "IA para concursos públicos africanos", tier: 4 }, { name: "IA para pequenas igrejas", tier: 4 }, { name: "IA para escolas privadas", tier: 4 },
  { name: "IA para clínicas pequenas", tier: 4 }, { name: "IA para oficinas mecânicas", tier: 4 }, { name: "IA para salões de beleza", tier: 4 },
  { name: "IA para taxistas", tier: 4 }, { name: "IA para mototaxistas", tier: 4 }, { name: "IA para imobiliárias locais", tier: 4 },
  { name: "IA para advogados independentes", tier: 4 }, { name: "IA para contadores", tier: 4 }, { name: "IA para professores particulares", tier: 4 },
  { name: "IA para criadores de cursos", tier: 4 }, { name: "IA para youtubers africanos", tier: 4 }, { name: "IA para influenciadores africanos", tier: 4 },
  { name: "IA para rádios locais", tier: 4 }, { name: "Sistema operacional pessoal baseado em IA", tier: 4 }, { name: "Rede social com IA integrada", tier: 4 },
  { name: "Tutor universal de IA", tier: 4 }, { name: "Aplicativo de carreira global", tier: 4 }, { name: "Marketplace global de agentes IA", tier: 4 },
  { name: "Plataforma de educação personalizada", tier: 4 }, { name: "Aplicativo de saúde preventiva IA", tier: 4 }, { name: "Aplicativo de produtividade total", tier: 4 },
  { name: "Aplicativo para criação automática de startups", tier: 4 }, { name: "Aplicativo que cria aplicativos por conversa", tier: 4 }, { name: "Tutor de IA para estudantes africanos", tier: 4 },
  { name: "Aplicativo anti-procrastinação gamificado", tier: 4 }, { name: "Criador de conteúdo para TikTok e YouTube por IA", tier: 4 }, { name: "Planeador financeiro pessoal com IA", tier: 4 },
  { name: "Coach de inglês com IA", tier: 4 }, { name: "Assistente para pequenos negócios", tier: 4 }, { name: "Gerador de aplicativos sem código", tier: 4 },
  { name: "Sistema de hábitos e disciplina", tier: 4 }, { name: "Gestor de carreira com IA", tier: 4 }, { name: "Plataforma de agentes IA especializados", tier: 4 },
  { name: "Universidade pessoal IA", tier: 4 }, { name: "Professor disponível 24 horas", tier: 4 }, { name: "Aprendizagem baseada em objetivos", tier: 4 },
  { name: "Aprendizagem por voz", tier: 4 }, { name: "Aprendizagem gamificada", tier: 4 }, { name: "Preparação para exames nacionais", tier: 4 },
  { name: "Preparação para concursos", tier: 4 }, { name: "Aprender qualquer profissão", tier: 4 }, { name: "Aprender através de simulações", tier: 4 },
  { name: "Mentor virtual permanente", tier: 4 }, { name: "Assistente para comerciantes de mercados", tier: 4 }, { name: "Assistente para agricultores familiares", tier: 4 },
  { name: "Assistente para taxistas", tier: 4 }, { name: "Assistente para mototaxistas", tier: 4 }, { name: "Assistente para pescadores", tier: 4 },
  { name: "Assistente para vendedores ambulantes", tier: 4 }, { name: "Assistente para pequenas lojas", tier: 4 }, { name: "Assistente para igrejas", tier: 4 },
  { name: "Assistente para escolas privadas", tier: 4 }, { name: "Assistente para clínicas locais", tier: 4 }, { name: "Mentor de carreira IA", tier: 4 },
  { name: "Conselheiro financeiro IA", tier: 4 }, { name: "Psicólogo digital IA", tier: 4 }, { name: "Treinador de hábitos IA", tier: 4 },
  { name: "Consultor de negócios IA", tier: 4 }, { name: "Gestor de estudos IA", tier: 4 }, { name: "Organizador familiar IA", tier: 4 },
  { name: "Assistente de compras IA", tier: 4 }, { name: "Gestor de energia pessoal IA", tier: 4 }, { name: "Planeador de vida IA", tier: 4 },
  { name: "IA pessoal (assistente de vida)", tier: 4 }, { name: "Planeamento de carreira com IA", tier: 4 }, { name: "Saúde mental assistida por IA", tier: 4 },
  { name: "Gestão financeira inteligente", tier: 4 }, { name: "Aprendizagem de inglês e competências profissionais", tier: 4 }, { name: "Ferramentas para criadores de conteúdo", tier: 4 },
  { name: "Gestão de pequenos negócios africanos", tier: 4 }, { name: "Sistemas anti-procrastinação e hábitos", tier: 4 }, { name: "Comunidades profissionais impulsionadas por IA", tier: 4 },
  { name: "IA que gere toda a vida do utilizador", tier: 4 }, { name: "IA que cria negócios automaticamente", tier: 4 }, { name: "IA que cria aplicações sem código", tier: 4 },
  { name: "IA que substitui um tutor humano", tier: 4 }, { name: "IA que planeia carreiras", tier: 4 }, { name: "IA que gere finanças pessoais", tier: 4 },
  { name: "IA que ajuda a encontrar emprego", tier: 4 }, { name: "IA que cria conteúdo viral", tier: 4 }, { name: "IA que constrói equipas de trabalho", tier: 4 },
  { name: "IA que coordena objetivos pessoais", tier: 4 }, { name: "IA que resume conteúdos", tier: 4 }, { name: "IA que cria conteúdos", tier: 4 },
  { name: "IA que cria negócios", tier: 4 }, { name: "IA que cria cursos", tier: 4 }, { name: "IA que cria aplicações", tier: 4 },
  { name: "IA que cria sites", tier: 4 }, { name: "IA que cria apresentações", tier: 4 }, { name: "IA que cria currículos", tier: 4 },
  { name: "IA que cria campanhas", tier: 4 }, { name: "IA que cria estratégias", tier: 4 }, { name: "Segunda memória com IA", tier: 4 },
  { name: "Tomada de decisões assistida por IA", tier: 4 }, { name: "Passar em exames", tier: 4 }, { name: "Conseguir certificações", tier: 4 },
  { name: "Aprender mais rápido", tier: 4 }, { name: "Automatizar tarefas", tier: 4 }, { name: "Conseguir clientes", tier: 4 },
  { name: "Melhorar gestão", tier: 4 }, { name: "Melhorar produtividade", tier: 4 }, { name: "Aumentar vendas", tier: 4 },
  { name: "Criar marca pessoal", tier: 4 }, { name: "Melhorar marketing", tier: 4 }, { name: "Crescer profissionalmente", tier: 4 },
  { name: "Implementar automação", tier: 4 }, { name: "Melhorar processos", tier: 4 }, { name: "Melhorar tomada de decisão", tier: 4 },
  { name: "Tornar-se referência", tier: 4 }, { name: "Viralizar conteúdo", tier: 4 }, { name: "Crescer no YouTube", tier: 4 },
  { name: "Crescer no TikTok", tier: 4 }, { name: "Aumentar engajamento", tier: 4 }, { name: "Criar comunidade", tier: 4 },
  { name: "Aumentar impacto", tier: 4 }, { name: "Escalar empresa", tier: 4 }, { name: "Tornar-se especialista", tier: 4 },
  { name: "Conseguir investidores", tier: 4 }, { name: "Trabalhar remotamente", tier: 4 }, { name: "Aumentar lucro", tier: 4 },
  { name: "Melhorar retenção", tier: 4 }, { name: "Melhorar planeamento", tier: 4 }, { name: "Aumentar rendimento", tier: 4 },
  { name: "Melhorar logística", tier: 4 }, { name: "Ganhar dinheiro", tier: 4 }, { name: "Poupar dinheiro", tier: 4 },
  { name: "Conseguir avaliações", tier: 4 }, { name: "Melhorar gestão de projetos", tier: 4 }, { name: "Conseguir promoção", tier: 4 },
  { name: "Melhorar qualidade de vida", tier: 4 }, { name: "Melhorar cuidados", tier: 4 }, { name: "Educar filhos", tier: 4 },
  { name: "Organizar vida pessoal", tier: 4 }, { name: "Melhorar organização", tier: 4 }, { name: "Fazer amigos", tier: 4 },
  { name: "Melhorar saúde", tier: 4 }, { name: "Encontrar emprego", tier: 4 }, { name: "Mudar de carreira", tier: 4 },
  { name: "Investir melhor", tier: 4 }, { name: "Construir património", tier: 4 }, { name: "Melhorar desempenho", tier: 4 },
  { name: "Melhorar hábitos", tier: 4 }, { name: "Melhorar resultados", tier: 4 }, { name: "Ganhar massa muscular", tier: 4 },
  { name: "Perder peso", tier: 4 }, { name: "Aprender inglês", tier: 4 }, { name: "Implementar IA", tier: 4 },
  { name: "Melhorar relacionamento", tier: 4 }, { name: "Encontrar parceiro", tier: 4 }, { name: "Recomeçar a vida", tier: 4 },
  { name: "Conseguir primeiro emprego", tier: 4 }, { name: "Aprovação", tier: 4 }, { name: "Automatizar recrutamento", tier: 4 },
  { name: "Automatizar atendimento", tier: 4 }, { name: "Aumentar conversões", tier: 4 }, { name: "Escolher carreira", tier: 4 },
  { name: "Conseguir emprego", tier: 4 }, { name: "Melhorar coordenação", tier: 4 }, { name: "Digitalizar negócios", tier: 4 },
  { name: "Aumentar ocupação", tier: 4 }, { name: "Conseguir oportunidades", tier: 4 }, { name: "Criar cursos rapidamente", tier: 4 },
  { name: "Gerar conteúdo viral", tier: 4 }, { name: "Aumentar visualizações", tier: 4 }, { name: "Aumentar audiência", tier: 4 },
  { name: "Aumentar comissões", tier: 4 }, { name: "Reduzir custos", tier: 4 }, { name: "Maximizar lucro", tier: 4 },
  { name: "Encontrar compradores", tier: 4 }, { name: "Otimizar entregas", tier: 4 }, { name: "Maximizar rendimento", tier: 4 },
  { name: "Organizar rotina", tier: 4 }, { name: "Melhorar educação", tier: 4 }, { name: "Criar rede social", tier: 4 },
  { name: "Criar networking", tier: 4 }, { name: "Fazer contactos", tier: 4 }, { name: "Construir carteira", tier: 4 },
  { name: "Melhorar decisões", tier: 4 }, { name: "Gerar clientes", tier: 4 }, { name: "Captar clientes", tier: 4 },
  { name: "Automatizar relatórios", tier: 4 }, { name: "Organizar consultas", tier: 4 }, { name: "Melhorar adesão", tier: 4 },
  { name: "Atender mais clientes", tier: 4 }, { name: "Melhorar bem-estar", tier: 4 }, { name: "Dormir melhor", tier: 4 },
  { name: "Criar rotina fitness", tier: 4 }, { name: "Falar fluentemente", tier: 4 }, { name: "Digitalizar operações", tier: 4 },
  { name: "Aumentar arrecadação", tier: 4 }, { name: "Garantir receita", tier: 4 }, { name: "Criar produtos digitais", tier: 4 },
  { name: "Criar programas online", tier: 4 }, { name: "Construir marca", tier: 4 }, { name: "Crescer audiência", tier: 4 },
  { name: "Monetizar arte", tier: 4 }, { name: "Melhorar performance", tier: 4 }, { name: "Escolher universidade", tier: 4 },
  { name: "Lançar negócio", tier: 4 }, { name: "Encontrar mercado", tier: 4 }, { name: "Aumentar receita", tier: 4 },
  { name: "Automatizar operações", tier: 4 }, { name: "Fechar mais negócios", tier: 4 }, { name: "Atrair talentos", tier: 4 },
  { name: "Digitalizar marketing", tier: 4 }, { name: "Atrair alunos", tier: 4 }, { name: "Melhorar permanência", tier: 4 },
  { name: "Encontrar oportunidades", tier: 4 }, { name: "Mudar de país", tier: 4 }, { name: "Organizar rendimentos", tier: 4 },
  { name: "Tomar melhores decisões", tier: 4 }, { name: "Crescer carreira", tier: 4 }, { name: "Ganhar tempo", tier: 4 },
  { name: "Aumentar rentabilidade", tier: 4 }, { name: "Encontrar casa", tier: 4 }, { name: "Comprar melhor", tier: 4 },
  { name: "Reduzir risks", tier: 4 }, { name: "Aumentar matrículas", tier: 4 }, { name: "Aumentar assinantes", tier: 4 },
  { name: "Crescer seguidores", tier: 4 }, { name: "Criar hábitos", tier: 4 }, { name: "Cumprir metas", tier: 4 },
  { name: "Planejar futuro", tier: 4 }, { name: "Sair das dívidas", tier: 4 }, { name: "Construir reserva", tier: 4 },
  { name: "Transformar ideias em projetos", tier: 4 }, { name: "Lançar produtos", tier: 4 }, { name: "Encontrar clientes", tier: 4 },
  { name: "Centralizar produtividade", tier: 4 },
  // Tier 5
  { name: "Análise Precisa de Sentimentos em Grandes Textos", tier: 5 }, { name: "Processamento de Linguagem Natural Avançado (NLP)", tier: 5 }, { name: "Machine Learning Preditivo Adaptável", tier: 5 },
  { name: "Classificação Automática Massiva de Imagens", tier: 5 }, { name: "Plataforma de Dados Unificados do Cliente (CDP)", tier: 5 }, { name: "Geração Dinâmica de Áudio Sob Demanda", tier: 5 },
  { name: "Chatbots Treinados com Base Privada Própria (RAG)", tier: 5 }, { name: "Segmentação Comportamental com Hiperpersonalização AI", tier: 5 },
  // Tier 6
  { name: "Visão Computacional de Alta Precisão (Análise de Vídeo)", tier: 6 }, { name: "Ecossistema de Agentes Autônomos de IA Colaborativos", tier: 6 }, { name: "Geração Renderizada de Vídeos e Avatares por IA", tier: 6 },
  { name: "Reconhecimento Facial Biométrico em Tempo Real", tier: 6 }, { name: "Análise Estruturadora de Dados Desordenados/Não-Estruturados", tier: 6 }, { name: "Clonagem de Voz de Alta Fidelidade (Deepfake de Áudio)", tier: 6 },
  { name: "Execução Autônoma de Smart Contracts (Web3/Blockchain)", tier: 6 }, { name: "Interfaces Nativas para Computação Espacial (AR/VR/Vision Pro)", tier: 6 }, { name: "Diagnóstico Clínico ou Mecânico Automatizado por Deep Learning", tier: 6 }
];
 
export const monetizations: Item[] = [
  // Tier 1
  { name: "Venda de Licença Única (Lifetime Deal)", tier: 1 }, { name: "Sistema Mantido por Doações/Patrocínios", tier: 1 }, { name: "Pagamento Unitário por Módulo Liberado", tier: 1 },
  // Tier 2
  { name: "Modelo de Agência (Você Vende Software + Serviço Acoplado)", tier: 2 }, { name: "Taxa de Manutenção Anual Simples", tier: 2 }, { name: "Cobrança de Setup Inicial Fixo + Mensalidade Muito Baixa", tier: 2 },
  // Tier 3
  { name: "Plano Anual com Forte Desconto de Retenção", tier: 3 }, { name: "Assinatura Semestral Bloqueada", tier: 3 }, { name: "Pacote de Créditos Pré-pagos que Expiram Mensalmente", tier: 3 },
  // Tier 4
  { name: "Assinatura Mensal Recorrente (O Padrão SaaS Clássico)", tier: 4 }, { name: "Plano Freemium com Upsell In-App Agressivo", tier: 4 }, { name: "Tiered Pricing Psicológico (Planos Bronze/Prata/Ouro)", tier: 4 },
  { name: "Cobrança Escalonável Baseada no Número de Usuários (Seats)", tier: 4 },
  // Tier 5
  { name: "Pay-per-use Direto (O Cliente Só Paga Exatamente o que Consome)", tier: 5 }, { name: "Cobrança Transparente por Volume Processado de Dados/APIs", tier: 5 }, { name: "Plano de Sucesso Baseado Exclusivamente no Crescimento da Empresa", tier: 5 },
  { name: "Cobrança de Alta Performance por Lead (Contato) Gerado", tier: 5 },
  // Tier 6
  { name: "Taxa Percentual Invisível sobre Transações (Efeito Marketplace)", tier: 6 }, { name: "Participação Genuína no Faturamento Adicional Gerado (Revenue Share)", tier: 6 }, { name: "Cobrança Atrelada ao ROI Direto Comprovado Pelo Software", tier: 6 },
  { name: "Economia Baseada em Tokenomics ou Rewards Criptografados", tier: 6 }
];
