"use client";

import { useLanguage } from "@/contexts/language-context";

export default function TermsPage() {
  const { language } = useLanguage();
  const isEn = language === 'en';
  const isEs = language === 'es';

  return (
    <div className="min-h-screen bg-background py-24 px-6">
      <div className="max-w-3xl mx-auto prose prose-neutral dark:prose-invert">
        <h1>{isEn ? "Terms of Use" : isEs ? "Términos de Uso" : "Termos de Uso"}</h1>
        <p><strong>{isEn ? "Last updated:" : isEs ? "Última actualización:" : "Última atualização:"} {new Date().toLocaleDateString(isEn ? 'en-US' : isEs ? 'es-ES' : 'pt-BR')}</strong></p>

        <p>
          {isEn 
            ? "Welcome to ViralBook AI. By accessing our site and using our services, you agree to these terms of use. Please read carefully." 
            : isEs 
            ? "Bienvenido a ViralBook AI. Al acceder a nuestro sitio y usar nuestros servicios, acepta estos términos de uso. Por favor lea atentamente." 
            : "Bem-vindo ao ViralBook AI. Ao acessar nosso site e utilizar nossos serviços, você concorda com estes termos de uso. Por favor, leia cuidadosamente."}
        </p>

        <h2>{isEn ? "1. Platform Usage" : isEs ? "1. Uso de la Plataforma" : "1. Uso da Plataforma"}</h2>
        <p>
          {isEn 
            ? "ViralBook AI provides access to market research tools and AI-driven idea generation. You agree to use the service only for lawful purposes." 
            : isEs 
            ? "ViralBook AI proporciona acceso a herramientas de investigación de mercado e generación de ideas impulsadas por IA. Acepta usar el servicio solo para fines legales." 
            : "O ViralBook AI fornece acesso a ferramentas de pesquisa de mercado e geração de ideias baseadas em inteligência artificial. Você concorda em usar o serviço apenas para propósitos legais."}
        </p>

        <h2>{isEn ? "2. Intellectual Property" : isEs ? "2. Propiedad Intelectual" : "2. Propriedade Intelectual"}</h2>
        <p>
          {isEn 
            ? "AI-generated business ideas (Lean Canvas) do not have copyright and can be freely modified and monetized by the user. However, source code, design, and branding belong exclusively to ViralBook AI." 
            : isEs 
            ? "Las ideas de negocio (Lean Canvas) generadas por IA no tienen derechos de autor y el usuario las puede utilizar libremente. Sin embargo, el código fuente y la marca pertenecen a ViralBook AI." 
            : "As ideias de negócio (Lean Canvas) geradas pela Inteligência Artificial não possuem direitos autorais e podem ser utilizadas, modificadas e monetizadas livremente pelo usuário. No entanto, o código-fonte, design e marca são de nossa propriedade intelectual."}
        </p>

        <h2>{isEn ? "3. Limitation of Liability" : isEs ? "3. Limitación de Responsabilidad" : "3. Limitação de Responsabilidade"}</h2>
        <p>
          {isEn 
            ? "Ideas and market insights are generated by AI (Groq/LLMs) based on public trend data. We do not guarantee financial success. Execution is the sole responsibility of the user." 
            : isEs 
            ? "Las ideas de SaaS y nichos son generadas por Inteligencia Artificial basadas en tendencias públicas. No garantizamos el éxito financiero." 
            : "As ideias de SaaS e nichos fornecidas pela plataforma são geradas por Inteligência Artificial (Groq/LLMs) baseadas em tendências públicas. Não garantimos sucesso financeiro."}
        </p>

        <h2>{isEn ? "4. Refund Policy (Guarantee)" : isEs ? "4. Reembolso (Garantía)" : "4. Reembolso (Garantia)"}</h2>
        <p>
          {isEn 
            ? "We offer an unconditional 7-day money-back guarantee. Contact support within 7 days for a full refund." 
            : isEs 
            ? "Ofrecemos una garantía incondicional de 7 días. Póngase en contacto con soporte para un reembolso completo." 
            : "Oferecemos uma garantia incondicional de 7 dias. Se você não estiver satisfeito com a plataforma dentro deste período, poderá solicitar um reembolso total."}
        </p>

        <h2>{isEn ? "5. Terms Modification" : isEs ? "5. Modificaciones de Términos" : "5. Modificações dos Termos"}</h2>
        <p>
          {isEn 
            ? "We reserve the right to modify these terms at any time. Continued use of the platform constitutes acceptance of changes." 
            : isEs 
            ? "Nos reservamos el derecho de modificar estos términos en cualquier momento." 
            : "Reservamo-nos o direito de alterar estes termos a qualquer momento. Seu uso continuado da plataforma constituirá sua aceitação das mudanças."}
        </p>

        <h2>{isEn ? "6. Contact" : isEs ? "6. Contacto" : "6. Contato"}</h2>
        <p>
          {isEn 
            ? "For questions regarding these Terms, contact us at: suporte@viralbook.ai" 
            : isEs 
            ? "Para preguntas sobre estos Términos, contáctenos en: suporte@viralbook.ai" 
            : "Para dúvidas relacionadas a estes Termos de Uso, entre em contato através de: suporte@viralbook.ai"}
        </p>
      </div>
    </div>
  );
}
